More work on getting cycles to have its bake function called.
Currently getting the following error:

Traceback (most recent call last):
File "/Users/dfelinto/blender/git/release/xcode/bin/Debug/blender.app/Contents/MacOS/2.69/scripts/addons/cycles/__init__.py",
line 71, in bake
   engine.bake(self, object, pass_type)
  File
"/Users/dfelinto/blender/git/release/xcode/bin/Debug/blender.app/Contents/MacOS/2.69/scripts/addons/cycles/engine.py",
line 66, in bake
    _cycles.bake(engine.session, object, pass_type)
TypeError: an integer is required